### ISSUE TITLE
Provide volume control

### ISSUE THREAD

**Issue by gerv** [FiveNinjas/SliceOS#30]
The Slice remote doesn't have buttons to control the volume and, other than the Mute function in the Power section of the main menu (which we triggered accidentally and had to read the FAQ to work out how to turn off) the skin doesn't provide any convenient way to set the volume either. This is very annoying, as we have to have the remote out for our amp just for those two buttons, so we can change the volume from the sofa.

Can volume controls be added somewhere convenient, perhaps on a menu, or as the functions of Up/Down when playing audio or video, or on the video overlay screen, or something?

Gerv

**Comment by ghollingworth** [comment]
Gerv,

Basically it is wrong to change the volume at the source because it will effect the quality of the audio that is being transmitted to the amplifier / TV.  Basically you can look at it as if there is a fairly constant background noise quantity, by reducing the volume at the source you are actually reducing the signal to noise ratio (which basically means the noise is increased whilst reducing the signal level)

It's also difficult because it will not effect both the normal throughput and encoded throughput paths (i.e. if you use passthrough then the volume control will not effect it)

Its the same with all analogue audio output signals from sources (just go and have a look at the DVD remote control it doesn't have a volume either).

One solution to this is to see whether CEC works with your TV remote control, if you get just the right combination of TV and amplifier connected up with HDMI then you should be able to use the TV remote control to work everything (including Slice)

Gordon

**Comment by gerv** [comment]
It may be wrong to change the volume at source, but it's very convenient for small adjustments! 

Our current audio path is HDMI -> TV, then digital optical -> amp and speakers. So we are not using analogue out from the Slice, so I don't think the noise thing is an issue, is it?

The TV also gives no control over the volume coming from its digital optical out - the TV volume control only affects its built-in speakers (which we have turned all the way down). 

We'd love to be able to set coarse volume on the amplifier, and then make adjustments using the Slice remote.

**Comment by cooltempo** [comment]
Hi Gerv. Doubt you'll be seeing volume control added by us. You could use a keyboard or alternate USB remote to access this through. Alternatively control volume of your amp via remote. These are your only options really :)

**Comment by tsonix** [comment]
Hello Gerv, 

There are some options for you here if you feel adventurous: 

1) If you have 2 buttons you want to 'sacrifice' in the existing slice remote, you can 'repoint' them to send the volume up/down commands to kodi (e.g. you can replace the ff/rw buttons). To do this have a look at http://kodi.wiki/view/Keyboard.xml (hopefully, this entails a few string replacements of something like "FastForward" to "VolumeUp"). 

2) Download a kodi remote for your mobile phone. The one I have for my iPhone is free and works fine.

3) Try entering the 'audio options' from the On screen display (OSD). At the very top, there are 2 volume sliders. They work for SOME types of media, not for all of them.

Hope this helps,
tsonix

**Comment by cecemf** [comment]
I agree with Gordon. This way is better. 

Audio control from the source is a nightmare. Do you control volume from you bluray player no? Well that's for the same reason. 

Universal remote like Harmony one or CEC is the best solution if you want one source of control.
