### ISSUE TITLE
Curious about streaming

### ISSUE THREAD

**Issue by Blkwolf89** [FiveNinjas/SliceOS#38]
I'm just curious has ever had any problems with trying to set up slice to stream from Windows Pc I haven't been able to use this feature and just wondering if anyone has been able to use it or has ever experienced this issue? If you have I for some reason have to enter some password and user name and i have no idea what they are and I can never get it to set up but yea just a curious issue thanks guys. i was wondering if it has become more stable and issues have been fixed this deals with SMB so yea thank you guys.

**Comment by ninyule** [comment]
For the thousandth time, the user name and password required is your Windows user and password, ie. what you use to log on. If you don't have a password, create one. If the name and password don't work, create another user account and password and use that. 

There is no issue or bug - I use this every day without problems. It is completely inappropriate to post here because it has NOTHING to do with bugtracking Slice!!

I even went to the trouble and producing a lengthy entry in the wiki (www.slicehowto.com) but even that does not seem to be enough. Please read the entry again and follow it to the letter - it works!!

**Comment by Blkwolf89** [comment]
you know that it's really rude how you treat a backer that helped fund
slice. This is not how you treat customers to are asking for support. It's
really disgusting that you get that aggravated when I'm asking to see if
anyone else has experienced that issue learn to have some professionalism
and grow the fuck up.

**Comment by ghollingworth** [comment]
Ninyule is not one of the FiveNinjas, he is a community member who's been putting his own time into the project for no payment.  I'm going to delete both posts and just point out that as Ninyule already did, this is a bug tracking system for identifying and tracking known problems with Slice rather than for discussion.

Please use the wiki for information on slice (that Ninyule wrote) for howto type help

www.slicehowto.com

and the forums for general discussion of how to use Slice

http://forums.fiveninjas.com/

Thanks

Gordon
